### ISSUE TITLE
requirements.txt file

### ISSUE THREAD

**Issue by a-t-h-i** [LonwaboMvovo/wordle-solver#3]
This is still a small project with only one dependency, but if you do somehow decide to use other Python libraries as the project becomes big (Turtle, Pygame etc...) it's best to have a requirement.txt file. So that a person who is interested in it doesn't have to manually install the dependencies one by one 😁.

**Comment by LonwaboMvovo** [comment]
Ya thanks👌 its a good practice...I'm gonna try doing this for all projects now
